---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rmp-redis-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rmp-redis-dev
  template:
    metadata:
      labels:
        app: rmp-redis-dev
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: role
                operator: In
                values:
                - worker-md
      containers:
        - name: rmp-redis-dev
          image: redis
          resources:
            limits:
              memory: "500Mi"
          imagePullPolicy: "IfNotPresent"
          args: ["--requirepass", "$(REDIS_PASS)", "--appendonly", "yes", "--save", "900", "1", "--save", "30", "2"]
          ports:
            - containerPort: 6379
          env:
            - name: REDIS_PASS
              valueFrom:
                secretKeyRef:
                  name: rmp-secret
                  key: redispassword
          volumeMounts:
            - mountPath: /data
              name: data-dir 
      volumes:
        - name: data-dir
          persistentVolumeClaim:
            claimName: rmp-redis-dev-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: rmp-redis-dev
  labels:
    app: rmp-redis-dev
spec:
  ports:
  - port: 6379
    protocol: TCP
  selector:
    app: rmp-redis-dev
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rmp-redis-dev-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 15Gi
