---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: school-scraper
spec:
  replicas: 10
  selector:
    matchLabels:
      app: school-scraper
  template:
    metadata:
      labels:
        app: school-scraper
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: role
                operator: In
                values:
                - worker-lg
                - worker-md
      containers:
        - name: school-scraper
          image: litcodes/school-scraper
          imagePullPolicy: "Always"
