---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: school-scraper
spec:
  replicas: 0
  selector:
    matchLabels:
      app: school-scraper
  template:
    metadata:
      labels:
        app: school-scraper
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: role
                operator: In
                values:
                - worker-lg
                - worker-md
      containers:
        - name: school-scraper
          image: litcodes/school-scraper
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          imagePullPolicy: "Always"
