---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: school-sql-applier
spec:
  replicas: 0
  selector:
    matchLabels:
      app: school-sql-applier
  template:
    metadata:
      labels:
        app: school-sql-applier
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: role
                operator: In
                values:
                - worker-lg
                - worker-md
      containers:
        - name: school-sql-applier
          image: litcodes/school-sql-applier
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          imagePullPolicy: "Always"
