---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: teacher-id-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teacher-id-generator
  template:
    metadata:
      labels:
        app: teacher-id-generator
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: role
                operator: In
                values:
                - worker-lg
      containers:
        - name: teacher-id-generator
          image: litcodes/teacher-id-generator
          imagePullPolicy: "Always"
          env:
          - name: BATCH_SIZE
            value: '800'
          - name: EMPTY_QUEUE_THRESHOLD
            value: '1200'
