---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: teacher-sql-generator
spec:
  replicas: 5
  selector:
    matchLabels:
      app: teacher-sql-generator
  template:
    metadata:
      labels:
        app: teacher-sql-generator
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: role
                operator: In
                values:
                - worker-lg
      containers:
        - name: teacher-sql-generator
          image: litcodes/teacher-sql-generator
          imagePullPolicy: "Always"
