---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: teacher-sql-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teacher-sql-generator
  template:
    metadata:
      labels:
        app: teacher-sql-generator
    spec:
      nodeSelector:
        role: worker-lg
      containers:
        - name: teacher-sql-generator
          image: litcodes/teacher-sql-generator
          imagePullPolicy: "Always"
