---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: teacher-scraper
spec:
  replicas: 2
  selector:
    matchLabels:
      app: teacher-scraper
  template:
    metadata:
      labels:
        app: teacher-scraper
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: role
                operator: In
                values:
                - worker-lg
      containers:
        - name: teacher-scraper
          image: litcodes/teacher-scraper
          imagePullPolicy: "Always"
          env:
            - name: REDIS_HOST
              value: rmp-redis-dev
            - name: USE_CURSOR
              value: 'true'
            - name: REDIS_PASS
              valueFrom:
                secretKeyRef:
                  name: rmp-secret
                  key: redispassword
            - name: DATA_DIR
              value: /data/ratings
          volumeMounts:
            - mountPath: /data
              name: data-dir
      volumes:
        - name: data-dir
          persistentVolumeClaim:
            claimName: teacher-scraper-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: teacher-scraper-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 30Gi
