---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: teacher-sql-applier
spec:
  replicas: 2
  selector:
    matchLabels:
      app: teacher-sql-applier
  template:
    metadata:
      labels:
        app: teacher-sql-applier
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: role
                operator: In
                values:
                - worker-lg
      containers:
        - name: teacher-sql-applier
          image: litcodes/teacher-sql-applier
          imagePullPolicy: "Always"
          env:
            - name: REDIS_HOST
              value: rmp-redis-dev
            - name: DB_HOST
              value: rmp-db-dev
            - name: DB_USER
              value: rmp
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: rmp-secret
                  key: dbpassword
            - name: REDIS_PASS
              valueFrom:
                secretKeyRef:
                  name: rmp-secret
                  key: redispassword
