---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rmp-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rmp-redis
  template:
    metadata:
      labels:
        app: rmp-redis
    spec:
      nodeSelector:
        role: primary
      containers:
        - name: rmp-redis
          image: redis
          imagePullPolicy: "IfNotPresent"
          args: ["--requirepass", "$(REDIS_PASS)", "--appendonly", "yes", "--save", "900", "1", "--save", "30", "2"]
          ports:
            - containerPort: 6379
          env:
            - name: REDIS_PASS
              valueFrom:
                secretKeyRef:
                  name: rmp-secret
                  key: redispassword
          volumeMounts:
            - mountPath: /data
              name: data-dir 
      volumes:
        - name: data-dir
          persistentVolumeClaim:
            claimName: rmp-redis-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: rmp-redis
  labels:
    app: rmp-redis
spec:
  ports:
  - port: 6379
    protocol: TCP
  selector:
    app: rmp-redis
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rmp-redis-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 15Gi
