apiVersion: v1
data:
  apisecret: MDE3NzVhODg4MmIxMmNlNmQyZDdhMmNiMGJhNzRmZjgxYmI4ZjI1ZTllZmMxMjg1OWE5NjRkZTUzZGJiZDU1OTgyNTg2NDA0MjBjYjdlYjE1MTEyNDZkZWY0MGRiMDBkZDk4YzNkODk0MjFmOWY3NGU4YTE5ZWZiNjk2ZmZhYWM=
  dbpassword: dmVyeXNlY3VyZXNlY3JldA==
  loginpassword: R3NkI2FTZiVYT3BMNDBuZUckNWlQeDMhanU=
  redispassword: dmVyeXNlY3VyZXNlY3JldA==
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"dbpassword":"dmVyeXNlY3VyZXNlY3JldAo=","redispassword":"dmVyeXNlY3VyZXNlY3JldAo="},"kind":"Secret","metadata":{"annotations":{},"name":"rmp-secret","namespace":"default"},"type":"Opaque"}
  creationTimestamp: "2020-05-29T00:27:59Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:apisecret: {}
        f:dbpassword: {}
        f:loginpassword: {}
        f:redispassword: {}
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
      f:type: {}
    manager: kubectl
    operation: Update
    time: "2020-05-30T08:31:56Z"
  name: rmp-secret
  namespace: default
  resourceVersion: "622629"
  selfLink: /api/v1/namespaces/default/secrets/rmp-secret
  uid: d223603b-8073-4e36-8302-db2e0cc96072
type: Opaque
