---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rmp-db-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rmp-db-worker
  template:
    metadata:
      labels:
        app: rmp-db-worker
    spec:
      nodeSelector:
        role: worker
      containers:
        - name: rmp-db-worker
          image: postgres:12
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: data-dir 
          env:
            - name: POSTGRES_DB
              value: rmp
            - name: POSTGRES_USER
              value: rmp
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rmp-secret
                  key: dbpassword
      volumes:
        - name: data-dir
          persistentVolumeClaim:
            claimName: rmp-db-worker-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: rmp-db-worker
  labels:
    app: rmp-db-worker
spec:
  ports:
  - port: 5432
    protocol: TCP
  selector:
    app: rmp-db-worker
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rmp-db-worker-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 15Gi
