---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: dev
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`rmp.lit.codes`)
    kind: Rule
    services:
    - name: rmp-prod
      port: 4000
  tls:
    secretName: cloudflarecrtsecret
