apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: testwebsite
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`test.lit.codes`)
    kind: Rule
    services:
    - name: nginx-deployment
      port: 80
  tls:
    secretName: cloudflarecrtsecret
