---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rmp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rmp
  template:
    metadata:
      labels:
        app: rmp
    spec:
      nodeSelector:
        role: primary
      containers:
        - name: rmp
          image: litcodes/rmp:amd64
          imagePullPolicy: "Always"
          ports:
            - containerPort: 4000
          env:
            - name: NODE_ENV
              value: production
            - name: REDIS_URL
              value: "redis://rmp-redis:6379"
            - name: CUBEJS_DB_HOST
              value: rmp-db
            - name: CUBEJS_DB_NAME
              value: rmp
            - name: CUBEJS_DB_USER
              value: rmp
            - name: CUBEJS_WEB_SOCKETS
              value: 'true'
            - name: CUBEJS_DB_TYPE
              value: postgres
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rmp-secret
                  key: redispassword
            - name: CUBEJS_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: rmp-secret
                  key: dbpassword
            - name: CUBEJS_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: rmp-secret
                  key: apisecret
            - name: LOGIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rmp-secret
                  key: loginpassword
---
apiVersion: v1
kind: Service
metadata:
  name: rmp
  labels:
    app: rmp
spec:
  ports:
  - port: 4000
    protocol: TCP
  selector:
    app: rmp
