---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: rmp-api
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
  - match: HostRegexp(`rmp.lit.codes`, `chartlib.com`, `{subdomain:[a-z]+}.chartlib.com`)
    kind: Rule
    services:
    - name: rmp
      port: 4000
  tls:
    secretName: cloudflarecrtsecret
