---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: rmp-api
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
  - match: HostRegexp(`rmp.lit.codes`, `chartlib.com`, `{subdomain:[a-z]+}.chartlib.com`)
    kind: Rule
    services:
    - name: rmp
      port: 4000
  tls:
    secretName: cloudflarecrtsecret
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: read-receipt
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`receipt.lit.codes`) && path(`/{call:[A-Za-z_-]+}/{img:[A-Za-z_-]+.png}`)
    middlewares:
    - name: receipt-basic-auth
      namespace: default
    kind: Rule
    services:
    - name: read-receipt
      port: 8080
  - match: Host(`receipt.lit.codes`) && path(`/stats`)
    middlewares:
    - name: receipt-basic-auth
      namespace: default
    kind: Rule
    services:
    - name: read-receipt
      port: 8080
  - match: Host(`receipt.lit.codes`) && path(`/{img:[A-Za-z_-]+.png}`)
    kind: Rule
    services:
    - name: read-receipt
      port: 8080
  tls:
    secretName: cloudflarecrtsecret
---
# More info: https://docs.traefik.io/middlewares/basicauth/
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: dev-basic-auth
  namespace: default
spec:
  basicAuth:
    secret: dev-secret
    namespace: default
---
# Note: in a kubernetes secret the string (e.g. generated by htpasswd) must be base64-encoded first.
# To create an encoded user:password pair, the following command can be used:
# htpasswd -nb user password | openssl base64

apiVersion: v1
kind: Secret
metadata:
  name: dev-secret
  namespace: default

data:
  users: |
      bmVnaW46JGFwcjEkTlZ2cVBiam8kOXNDaUo4SmdYUFJrTnpQTXROcS5YLwoKYW1pbjokYXByMSR5
      VVBSdnlocyRzUElqLko5V0NEY1o3NE9iL080ZDAwCgpzYWVlZDokYXByMSQ3Z1FvTHdjYSRDU2Fh
      cmc5RGRWbkd6QXpEM3JEckYxCgpnYWdpazokYXByMSRsMjJhMnhBTiRXTFdubm5DWVNPLjZQN1lZ
      c1hMYlEwCgo=
---
# More info: https://docs.traefik.io/middlewares/basicauth/
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: receipt-basic-auth
  namespace: default
spec:
  basicAuth:
    secret: receipt-secret
    namespace: default
---
apiVersion: v1
kind: Secret
metadata:
  name: receipt-secret
  namespace: default

data:
  users: YWRtaW46JGFwcjEkUFRyOTUvTTckL2pCU1F2SGtyeXNCVGt1UFlpcnRHLwoK

