apiVersion: v1
kind: Service
metadata:
  name: traefik

spec:
  selector:
    app: traefik
  type: NodePort
  externalIPs:
  - 54.254.252.35
  ports:
    - protocol: TCP
      name: websecure
      port: 443
      nodePort: 443
