---

- hosts: k3s_cluster
  gather_facts: yes
  become: yes
  roles:
    - role: prereq
    - role: download
    - role: wireguard

- hosts: master
  become: yes
  roles:
    - role: ubuntu
    - role: k3s/master

- hosts: pi
  become: yes
  roles:
    - role: raspbian

- hosts: node
  become: yes
  roles:
    - role: k3s/node
